name: Keep Render Awake

on:
  schedule:
    - cron: "*/12 * * * *"   # cada 12 minutos
  workflow_dispatch:          # permite lanzarlo a mano

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping público /ping (sin auth)
        run: |
          curl -sSf https://solfico-bitrix-wkkc.onrender.com/ping

      - name: Ping privado /api/hello (con auth)
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -sSf -H "Authorization: Bearer ${API_KEY}" https://solfico-bitrix-wkkc.onrender.com/api/hello
